<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\BilanReferenceMapping;

class BilanReferenceMappingSeeder extends Seeder
{
    public function run()
    {
        $mappings = [
            // PASSIF
            ['CA', '101000', 'Dotation non consomptible sans droit reprise'],
            ['CA', '101100', 'en numéraire'],
            ['CA', '101500', 'en nature'],
            
            ['CB', '102000', 'Dotation non consomptible avec droit reprise'],
            ['CB', '102100', 'en numéraire'],
            ['CB', '102500', 'en nature'],
            
            ['CC', '103000', 'Droit d\'entrée'],
            
            ['CD', '104000', 'Dotation consomptible'],
            ['CD', '104100', 'Dotation consomptible'],
            ['CD', '104900', 'Dotation consomptible inscrite au compte de résultat'],
            
            ['CE', '106000', 'Écarts de réévaluation'],
            ['CE', '106100', 'Écarts de réévaluation sur des biens sans droit de reprise'],
            ['CE', '106110', 'Écarts de réévaluation sur des biens sans droit de reprise-immobilisations corporelles'],
            ['CE', '106120', 'Écarts de réévaluation sur des biens sans droit de reprise-immobilisations financières'],
            ['CE', '106200', 'Écarts de réévaluation sur des biens avec droit de reprise'],
            ['CE', '106210', 'Écarts de réévaluation sur des biens avec droit de reprise-immobilisations corporelles'],
            ['CE', '106220', 'Écarts de réévaluation sur des biens avec droit de reprise-immobilisations financières'],
            
            ['CF', '112000', 'Réserves statutaires ou contractuelles'],
            ['CF', '118000', 'Autres réserves'],
            
            ['CG', '121000', 'Report à nouveau des excédents'],
            ['CG', '128000', 'Résultat en instance d\'affectation'],
            ['CG', '129000', 'Report à nouveau des déficits'],
            
            ['CH', '131000', 'Excédent de l\'exercice'],
            ['CH', '139000', 'Déficit de l\'exercice'],
            
            ['CI', '141000', 'Subventions d\'équipement'],
            ['CI', '141100', 'État'],
            ['CI', '141200', 'Régions'],
            ['CI', '141300', 'Départements'],
            ['CI', '141400', 'Communes et collectivités publiques décentralisées'],
            ['CI', '141500', 'Entités publiques ou mixtes'],
            ['CI', '141600', 'Entités et organismes privés'],
            ['CI', '141700', 'Organismes internationaux'],
            ['CI', '141800', 'Autres'],
            ['CI', '148000', 'Autres subventions d\'investissement'],
            
            ['CJ', '154000', 'Provisions spéciales de réévaluation'],
            ['CJ', '158000', 'Autres provisions réglementées et fonds assimilés'],
            
            ['CW', '161000', 'Fonds projet de développement - avances de fonds à justifier'],
            ['CW', '162000', 'Fonds affectés aux investissements du projet de développement - bailleurs de fonds'],
            ['CW', '163000', 'Fonds affectés aux investissements du projet de développement - l\'Etat'],
            ['CW', '164000', 'Fonds affectés aux investissements des autres organismes de financement assimilés'],
            ['CW', '165000', 'Fonds non consommés en fin d\'exercice destinés à un projet spécifique'],
            ['CW', '167000', 'Fonds provenant de dons et legs d\'immobilisations'],
            ['CW', '167100', 'affectés'],
            ['CW', '167200', 'non affectés'],
            ['CW', '167900', 'Engagements auprès donateur'],
            ['CW', '168000', 'Autres fonds affectés'],
            ['CW', '169000', 'Fonds affectés à recevoir'],
            
            ['CX', '171000', 'Donation temporaire d\'usufruit'],
            ['CX', '172000', 'Donations et legs d\'immobilisations non reçus destinés à la vente'],
            ['CX', '178000', 'Autres fonds reportés'],
            
            ['DA', '181000', 'Emprunts obligataires'],
            ['DA', '182000', 'Emprunts et dettes auprès des établissements de crédit'],
            ['DA', '183000', 'Avances reçues de l\'État'],
            ['DA', '185000', 'Dépôts et cautionnements reçus'],
            ['DA', '185100', 'Dépôts'],
            ['DA', '185200', 'Cautionnements'],
            ['DA', '186000', 'Intérêts courus'],
            ['DA', '186100', 'Sur emprunts obligataires'],
            ['DA', '186200', 'sur emprunts et dettes auprès des établissements de crédit'],
            ['DA', '186300', 'sur avances reçues de l\'État'],
            ['DA', '186500', 'sur dépôts et cautionnements reçus'],
            ['DA', '186800', 'sur autres emprunts et dettes'],
            ['DA', '188000', 'Autres emprunts et dettes'],
            
            ['DB', '187000', 'Dettes de location-acquisition'],
            ['DB', '187100', 'Dettes de location-acquisition/ crédit-bail immobilier'],
            ['DB', '187200', 'Dettes de location-acquisition/ crédit-bail mobilier'],
            ['DB', '187300', 'Dettes de location-acquisition /location-vente'],
            ['DB', '187600', 'Intérêts courus'],
            
            ['DC', '191000', 'Provisions pour litiges'],
            ['DC', '192000', 'Provisions pour charges sur donations et legs'],
            ['DC', '194000', 'Provisions pour pertes de change'],
            ['DC', '196000', 'Provisions pour pensions et obligations similaires'],
            ['DC', '198000', 'Autres provisions pour risques et charges'],
            ['DC', '198100', 'Provisions pour amendes et pénalités'],
            ['DC', '198400', 'Provisions pour démantèlement et remise en état'],
            ['DC', '198800', 'Provisions pour divers risques et charges'],
            
            // ACTIF
            ['AB', '201000', 'Immobilisations incorporelles'],
            ['AB', '201100', 'Usufruit temporaire'],
            ['AB', '201200', 'Brevets, licences, concessions et droits similaires'],
            ['AB', '201300', 'Logiciels et sites informatiques'],
            ['AB', '201400', 'Marques'],
            ['AB', '201700', 'Autres'],
            
            ['AC', '202000', 'Terrains'],
            ['AC', '203000', 'Bâtiments'],
            ['AC', '204000', 'Matériels'],
            ['AC', '205000', 'Titres de participations'],
            
            ['AE', '212000', 'Brevets, licences, concessions et droits similaires'],
            ['AE', '212100', 'Brevets'],
            ['AE', '212200', 'Licences'],
            ['AE', '212300', 'Concessions de service public'],
            ['AE', '212800', 'Autres concessions et droits similaires'],
            ['AE', '213000', 'Logiciels et sites internet'],
            ['AE', '213100', 'Logiciels'],
            ['AE', '213200', 'Sites internet'],
            ['AE', '214000', 'Marques'],
            ['AE', '219300', 'Logiciels et sites internet'],
            
            ['AF', '218000', 'Autres droits et valeurs incorporels'],
            ['AF', '218100', 'Indemnités de transfert aux joueurs'],
            ['AF', '219000', 'Immobilisations incorporelles en cours'],
            ['AF', '219800', 'Autres droits et valeurs incorporels'],
            
            ['AG', '251000', 'Avances et acomptes versés sur immobilisations incorporelles'],
            
            ['AI', '221000', 'Terrains agricoles et forestiers'],
            ['AI', '221100', 'Terrains d\'exploitation agricole'],
            ['AI', '221200', 'Terrains d\'exploitation forestière'],
            ['AI', '221800', 'Autres terrains'],
            ['AI', '222000', 'Terrains nus'],
            ['AI', '222100', 'Terrains à bâtir'],
            ['AI', '222800', 'Autres terrains nus'],
            ['AI', '223000', 'Terrains bâtis'],
            ['AI', '223100', 'pour bâtiments industriels et agricoles'],
            ['AI', '223200', 'pour bâtiments administratifs et commerciaux'],
            ['AI', '223400', 'pour bâtiments affectés aux autres opérations professionnelles'],
            ['AI', '223500', 'pour bâtiments affectés aux autres opérations non professionnelles'],
            ['AI', '223800', 'Autres terrains bâtis'],
            ['AI', '224000', 'Travaux de mise en valeur des terrains'],
            ['AI', '224100', 'Plantation d\'arbres et d\'arbustes'],
            ['AI', '224500', 'Améliorations du fonds'],
            ['AI', '224800', 'Autres travaux'],
            ['AI', '226000', 'Terrains aménagés'],
            ['AI', '226100', 'Parkings'],
            ['AI', '228000', 'Autres terrains'],
            ['AI', '228100', 'Terrains - immeubles de placement'],
            ['AI', '228500', 'Terrains des logements affectés au personnel'],
            ['AI', '228600', 'Terrains de location - acquisition'],
            ['AI', '228800', 'Divers terrains'],
            ['AI', '229000', 'Aménagements de terrains en cours'],
            ['AI', '229100', 'Terrains agricoles et forestiers'],
            ['AI', '229200', 'Terrains nus'],
            ['AI', '229800', 'Autres terrains'],
            
            ['AJ', '231000', 'Bâtiments industriels, agricoles, administratifs, commerciaux, religieux et autres sur sol propre'],
            ['AJ', '231100', 'Bâtiments industriels'],
            ['AJ', '231200', 'Bâtiments agricoles'],
            ['AJ', '231300', 'Bâtiments administratifs et commerciaux'],
            ['AJ', '231400', 'Bâtiments affectés au logement du personnel'],
            ['AJ', '231500', 'Bâtiments - immeubles de placement'],
            ['AJ', '231600', 'Bâtiments de location – acquisition'],
            ['AJ', '231700', 'Edifices religieux et assimilés'],
            ['AJ', '231800', 'Autres bâtiments sur sol propre'],
            ['AJ', '232000', 'Bâtiments industriels, agricoles, administratifs, commerciaux, religieux et autres sur sol d\'autrui'],
            ['AJ', '232100', 'Bâtiments industriels'],
            ['AJ', '232200', 'Bâtiments agricoles'],
            ['AJ', '232300', 'Bâtiments administratifs et commerciaux'],
            ['AJ', '232400', 'Bâtiments affectés au logement du personnel'],
            ['AJ', '232500', 'Bâtiments - immeubles de placement'],
            ['AJ', '232600', 'Bâtiments de location - acquisition'],
            ['AJ', '232700', 'Edifices religieux et assimilés'],
            ['AJ', '232800', 'Autres bâtiments sur sol d\'autrui'],
            ['AJ', '233000', 'Ouvrages d\'infrastructure'],
            ['AJ', '233100', 'Voies de terre'],
            ['AJ', '233200', 'Voies de fer'],
            ['AJ', '233300', 'Voies d\'eau'],
            ['AJ', '233400', 'Barrages, digues'],
            ['AJ', '233500', 'Pistes d\'aérodrome'],
            ['AJ', '233700', 'Stades et autres infrastructures sportives'],
            ['AJ', '233800', 'Autres ouvrages d\'infrastructures'],
            ['AJ', '239100', 'Bâtiments sur sol propre en cours'],
            ['AJ', '239200', 'Bâtiments sur sol d\'autrui en cours'],
            ['AJ', '239300', 'Ouvrages d\'infrastructure en cours'],
            ['AJ', '239600', 'Bâtiments en cours-immeubles de placement'],
            
            ['AK', '234000', 'Aménagements, agencements et installations techniques'],
            ['AK', '234100', 'Installations complexes spécialisées sur sol propre'],
            ['AK', '234200', 'Installations complexes spécialisées sur sol d\'autrui'],
            ['AK', '234300', 'Installations à caractère spécifique sur sol propre'],
            ['AK', '234400', 'Installations à caractère spécifique sur sol d\'autrui'],
            ['AK', '234500', 'Aménagements et agencements des bâtiments'],
            ['AK', '235000', 'Aménagements de bureaux et assimilés'],
            ['AK', '235100', 'Installations générales'],
            ['AK', '235800', 'Autres aménagements de bureaux'],
            ['AK', '238000', 'Autres installations et agencements'],
            ['AK', '238100', 'Autres installations et agencements des édifices religieux et assimilés'],
            ['AK', '238200', 'Autres installations et agencements des stades et autres infrastructures sportives'],
            ['AK', '239000', 'Bâtiments, aménagements, agencements et installations en cours'],
            ['AK', '239400', 'Aménagements, agencements et installations techniques en cours'],
            ['AK', '239500', 'Aménagements de bureaux en cours'],
            ['AK', '239800', 'Autres installations et agencements en cours'],
            
            ['AL', '241000', 'Matériel et outillage industriel et commercial'],
            ['AL', '241100', 'Matériel industriel'],
            ['AL', '241200', 'Outillage industriel'],
            ['AL', '241300', 'Matériel commercial'],
            ['AL', '241400', 'Outillage commercial'],
            ['AL', '241600', 'Matériel et outillage industriel et commercial de location – acquisition'],
            ['AL', '242000', 'Matériel et outillage agricole'],
            ['AL', '242100', 'Matériel agricole'],
            ['AL', '242200', 'Outillage agricole'],
            ['AL', '242600', 'Matériel et outillage agricole de location-acquisition'],
            ['AL', '243000', 'Matériel d\'emballage récupérable et identifiable'],
            ['AL', '244000', 'Matériel et mobilier'],
            ['AL', '244100', 'Matériel et mobilier de bureau'],
            ['AL', '244200', 'Matériel informatique et bureautique'],
            ['AL', '244300', 'Matériel et mobilier religieux'],
            ['AL', '244400', 'Matériel et mobilier sportifs'],
            ['AL', '244500', 'Matériel et mobilier - immeubles de placement'],
            ['AL', '244600', 'Matériel et mobilier de location - acquisition'],
            ['AL', '244700', 'Matériel et mobilier des logements du personnel'],
            ['AL', '246000', 'Actifs biologiques'],
            ['AL', '246100', 'Cheptel, animaux de trait'],
            ['AL', '246200', 'Cheptel, animaux reproducteurs'],
            ['AL', '246300', 'Animaux de garde'],
            ['AL', '246500', 'Plantations agricoles'],
            ['AL', '246800', 'Autres actifs biologiques'],
            ['AL', '247000', 'Agencements, aménagements du matériel et des actifs biologiques'],
            ['AL', '247100', 'Agencements et aménagements du matériel'],
            ['AL', '247200', 'Agencements et aménagements des actifs biologiques'],
            ['AL', '247800', 'Autres agencements, aménagements du matériel et des actifs biologiques'],
            ['AL', '248000', 'Autres matériels et mobiliers'],
            ['AL', '248100', 'Collections et œuvres d\'art'],
            ['AL', '248800', 'Divers matériels et mobiliers'],
            ['AL', '249000', 'Matériels et actifs biologiques en cours'],
            ['AL', '249100', 'Matériel et outillage industriel et commercial'],
            ['AL', '249200', 'Matériel et outillage agricole'],
            ['AL', '249300', 'Matériel d\'emballage récupérable et identifiable'],
            ['AL', '249400', 'Matériel et mobilier de bureau'],
            ['AL', '249600', 'Actifs biologiques'],
            ['AL', '249700', 'Agencements et aménagements du matériel et des actifs biologiques'],
            ['AL', '249800', 'Autres matériels et actifs biologiques'],
            
            ['AM', '245000', 'Matériel de transport'],
            ['AM', '245100', 'Matériel automobile'],
            ['AM', '245200', 'Matériel ferroviaire'],
            ['AM', '245300', 'Matériel fluvial, lagunaire'],
            ['AM', '245400', 'Matériel naval'],
            ['AM', '245500', 'Matériel aérien'],
            ['AM', '245600', 'Matériel de transport de location - acquisition'],
            ['AM', '245700', 'Matériel hippomobile'],
            ['AM', '245800', 'Autres matériels de transport'],
            ['AM', '249500', 'Matériel de transport'],
            
            ['AN', '252000', 'Avances et acomptes versés sur immobilisations corporelles'],
            
            ['AX', '261000', 'Titres de participation'],
            ['AX', '265000', 'Participations dans des organismes professionnels'],
            ['AX', '266000', 'Parts dans des groupements d\'intérêt économique (G.I.E.)'],
            ['AX', '268000', 'Autres titres de participation'],
            
            ['AY', '271000', 'Prêts et créances'],
            ['AY', '271100', 'Prêts participatifs'],
            ['AY', '271300', 'Billets de fonds'],
            ['AY', '271500', 'Titres prêtés'],
            ['AY', '271800', 'Autres prêts et créances'],
            ['AY', '272000', 'Prêts au personnel'],
            ['AY', '272100', 'Prêts immobiliers'],
            ['AY', '272200', 'Prêts mobiliers et d\'installation'],
            ['AY', '272800', 'Autres prêts au personnel'],
            ['AY', '273000', 'Créances sur l\'Etat'],
            ['AY', '273100', 'Retenues de garantie'],
            ['AY', '273300', 'Fonds réglementé'],
            ['AY', '273800', 'Autres créances sur l\'Etat'],
            ['AY', '274000', 'Titres immobilisés'],
            ['AY', '274100', 'Titres immobilisés de l\'activité de portefeuille (T.I.A.P.)'],
            ['AY', '274200', 'Titres participatifs'],
            ['AY', '274300', 'Certificats d\'investissement'],
            ['AY', '274400', 'Parts de fonds commun de placement (F.C.P.)'],
            ['AY', '274500', 'Obligations'],
            ['AY', '274800', 'Autres titres immobilisés'],
            ['AY', '275000', 'Dépôts et cautionnements versés'],
            ['AY', '275100', 'Dépôts pour loyers d\'avance'],
            ['AY', '275200', 'Dépôts pour l\'électricité'],
            ['AY', '275300', 'Dépôts pour l\'eau'],
            ['AY', '275400', 'Dépôts pour le gaz'],
            ['AY', '275500', 'Dépôts pour le téléphone, la télécopie'],
            ['AY', '275800', 'Autres dépôts et cautionnement'],
            ['AY', '276000', 'Intérêts courus'],
            ['AY', '276100', 'Prêts et créances'],
            ['AY', '276200', 'Prêts au personnel'],
            ['AY', '276300', 'Créances sur l\'Etat'],
            ['AY', '276400', 'Titres immobilisés'],
            ['AY', '276500', 'Dépôts et cautionnements versés'],
            ['AY', '276800', 'Immobilisations financières diverses'],
            ['AY', '278000', 'Immobilisations financières diverses'],
            ['AY', '278100', 'Créances diverses'],
            ['AY', '278400', 'Banques dépôts à terme et opérations assimilées'],
            ['AY', '278500', 'Or et métaux précieux(1)'],
            ['AY', '278800', 'Autres immobilisations financières'],
            
            // AMORTISSEMENTS ET DEPRECIATIONS
            ['AB', '280000', 'Amortissements de l\'usufruit temporaire'],
            ['AB', '290000', 'Dépréciations des immobilisations non reçues destinées à la vente provenant de dons et legs et usufruit temporaire'],
            ['AB', '290100', 'Dépréciations de l\'usufruit temporaire'],
            
            ['AC', '290200', 'Dépréciations des immobilisations non reçues destinées à la vente provenant de dons et legs'],
            
            ['AE', '281000', 'Amortissements des immobilisations incorporelles'],
            ['AE', '281200', 'Amortissements des brevets, licences, concessions et droits similaires'],
            ['AE', '281300', 'Amortissements des logiciels et sites internet'],
            ['AE', '281400', 'Amortissements des marques'],
            ['AE', '291000', 'Dépréciations des immobilisations incorporelles'],
            ['AE', '291200', 'Dépréciations des brevets, licences, concessions et droits similaires'],
            ['AE', '291300', 'Dépréciations des logiciels et sites internet'],
            ['AE', '291400', 'Dépréciations des marques'],
            ['AE', '291900', 'Dépréciations des immobilisations incorporelles en cours'],
            
            ['AF', '281700', 'Amortissements des Indemnités de transfert aux joueurs'],
            ['AF', '281800', 'Amortissements des autres droits et valeurs incorporels'],
            ['AF', '291800', 'Dépréciations des autres droits et valeurs incorporels'],
            
            ['AI', '282000', 'Amortissements des terrains'],
            ['AI', '282400', 'Amortissements des travaux de mise en valeur des terrains'],
            ['AI', '292000', 'Dépréciations des terrains'],
            ['AI', '292100', 'Dépréciations des terrains agricoles et forestiers'],
            ['AI', '292200', 'Dépréciations des terrains nus'],
            ['AI', '292300', 'Dépréciations des terrains bâtis'],
            ['AI', '292400', 'Dépréciations des travaux de mise en valeur des terrains'],
            ['AI', '292600', 'Dépréciations des terrains aménagés'],
            ['AI', '292800', 'Dépréciations des autres terrains'],
            ['AI', '292900', 'Dépréciations des aménagements de terrains en cours'],
            
            ['AJ', '283000', 'Amortissements des bâtiments, installations techniques et agencements'],
            ['AJ', '283100', 'Amortissements des bâtiments industriels, agricoles, administratifs, commerciaux, religieux et autres sur sol propre'],
            ['AJ', '283200', 'Amortissements des bâtiments industriels, agricoles, administratifs, commerciaux, religieux et autres sur sol d\'autrui'],
            ['AJ', '283300', 'Amortissements des ouvrages d\'infrastructure'],
            ['AJ', '293000', 'Dépréciations des bâtiments, installations techniques et agencements'],
            ['AJ', '293100', 'Dépréciations des bâtiments industriels, agricoles, administratifs, commerciaux, religieux et autres sur sol propre'],
            ['AJ', '293200', 'Dépréciations des bâtiments industriels, agricoles, administratifs, commerciaux, religieux et autres sur sol d\'autrui'],
            ['AJ', '293300', 'Dépréciations des ouvrages d\'infrastructures'],
            ['AJ', '293900', 'Dépréciations des bâtiments et installations en cours'],
            
            ['AK', '283400', 'Amortissements des aménagements, agencements et installations techniques'],
            ['AK', '283500', 'Amortissements des aménagements de bureaux'],
            ['AK', '283800', 'Amortissements des autres installations et agencements'],
            ['AK', '293400', 'Dépréciations des aménagements, agencements et installations techniques'],
            ['AK', '293500', 'Dépréciations des aménagements de bureaux'],
            ['AK', '293800', 'Dépréciations des autres installations et agencements'],
            
            ['AL', '284000', 'Amortissements du matériel'],
            ['AL', '284100', 'Amortissements du matériel et de l\'outillage industriel et commercial'],
            ['AL', '284200', 'Amortissements du matériel et de l\'outillage agricole'],
            ['AL', '284300', 'Amortissements du matériel d\'emballage récupérable et identifiable'],
            ['AL', '284400', 'Amortissements du matériel et du mobilier'],
            ['AL', '284600', 'Amortissements des actifs biologiques'],
            ['AL', '284700', 'Amortissements des agencements et aménagements du matériel et des actifs biologiques'],
            ['AL', '284800', 'Amortissements des autres matériels'],
            ['AL', '294000', 'Dépréciations de matériel, du mobilier et de l\'actif biologique'],
            ['AL', '294100', 'Dépréciations du matériel et de l\'outillage industriel et commercial'],
            ['AL', '294200', 'Dépréciations du matériel et de l\'outillage agricole'],
            ['AL', '294300', 'Dépréciations du matériel d\'emballage récupérable et identifiable'],
            ['AL', '294400', 'Dépréciations du matériel et du mobilier'],
            ['AL', '294600', 'Dépréciations des actifs biologiques'],
            ['AL', '294700', 'Dépréciations des aménagements et agencements du matériel et des actifs biologiques'],
            ['AL', '294800', 'Dépréciations des autres matériels'],
            ['AL', '294900', 'Dépréciations de matériel en cours'],
            
            ['AM', '284500', 'Amortissements du matériel de transport'],
            ['AM', '294500', 'Dépréciations du matériel de transport'],
            
            ['AG', '295100', 'Dépréciations des avances et acomptes versés sur immobilisations incorporelles'],
            
            ['AN', '295200', 'Dépréciations des avances et acomptes versés sur immobilisations corporelles'],
            
            ['AX', '296000', 'Dépréciations des titres de participation'],
            ['AX', '296100', 'Dépréciations des titres de participation'],
            ['AX', '296500', 'Dépréciations des participations dans des organismes professionnels'],
            ['AX', '296600', 'Dépréciations des parts dans des GIE'],
            ['AX', '296800', 'Dépréciations des autres titres de participation'],
            
            ['AY', '297000', 'Dépréciations des autres immobilisations financières'],
            ['AY', '297100', 'Dépréciations des prêts et créances'],
            ['AY', '297200', 'Dépréciations des prêts au personnel'],
            ['AY', '297300', 'Dépréciations des créances sur l\'Etat'],
            ['AY', '297400', 'Dépréciations des titres immobilisés'],
            ['AY', '297500', 'Dépréciations des dépôts et cautionnements versés'],
            ['AY', '297700', 'Dépréciations des créances rattachées à des participations et avances à des GIE'],
            ['AY', '297800', 'Dépréciations des créances financières diverses'],
            
            // STOCKS
            ['BB', '311000', 'Biens liés à l\'activité A'],
            ['BB', '312000', 'Biens liés à l\'activité B'],
            ['BB', '321000', 'Marchandises A'],
            ['BB', '322000', 'Marchandises B'],
            ['BB', '323000', 'Matières A'],
            ['BB', '324000', 'Matières B'],
            ['BB', '325000', 'Fournitures liées (A, B)'],
            ['BB', '331000', 'Matières consommables'],
            ['BB', '333000', 'Fournitures de magasin'],
            ['BB', '334000', 'Fournitures de bureau'],
            ['BB', '335000', 'Emballages'],
            ['BB', '335100', 'Emballages perdus'],
            ['BB', '335200', 'Emballages récupérables non identifiables'],
            ['BB', '335300', 'Emballages à usage mixte'],
            ['BB', '335800', 'Autres emballages'],
            ['BB', '338000', 'Autres matières'],
            ['BB', '341000', 'Dons en nature non affectés'],
            ['BB', '345000', 'Dons en nature affectés'],
            ['BB', '361000', 'Produits finis A'],
            ['BB', '362000', 'Produits finis B'],
            ['BB', '363000', 'Actifs biologiques'],
            ['BB', '363100', 'Animaux'],
            ['BB', '363200', 'Végétaux'],
            ['BB', '363800', 'Autres stocks (activités annexes)'],
            ['BB', '367000', 'Produits intermédiaires et résiduels'],
            ['BB', '371000', 'Biens liés à l\'activité en cours de route'],
            ['BB', '372000', 'Marchandises, matières premières et fournitures liés en cours de route'],
            ['BB', '373000', 'Autres approvisionnements en cours de route'],
            ['BB', '376000', 'Produits finis en cours de route'],
            ['BB', '377000', 'Stocks en consignation ou en dépôt'],
            ['BB', '377100', 'Stock en consignation'],
            ['BB', '377200', 'Stock en dépôt'],
            ['BB', '378000', 'Stock provenant d\'immobilisations mises hors services ou au rebut'],
            ['BB', '381000', 'non affectés'],
            ['BB', '385000', 'affectés'],
            
            ['BB', '391000', 'Dépréciations des stocks de biens liés à l\'activité'],
            ['BB', '392000', 'Dépréciations des stocks de marchandises, et matières premières et fournitures liées'],
            ['BB', '393000', 'Dépréciations des stocks d\'autres approvisionnements'],
            ['BB', '396000', 'Dépréciations des stocks de produits finis, produits intermédiaires et résiduels'],
            ['BB', '397000', 'Dépréciations des stocks en cours de route, en consignation ou en dépôt'],
            
            // COMPTES DE TIERS
            ['DH', '401000', 'Fournisseurs, dettes en compte'],
            ['DH', '401100', 'Fournisseurs'],
            ['DH', '401300', 'Fournisseurs sous-traitants'],
            ['DH', '401600', 'Fournisseurs, réserve de propriété'],
            ['DH', '401700', 'Fournisseurs, retenues de garantie'],
            ['DH', '402000', 'Fournisseurs, effets à payer'],
            ['DH', '402100', 'Fournisseurs, effets à payer'],
            ['DH', '402300', 'Fournisseurs sous-traitants, effets à payer'],
            ['DH', '408000', 'Fournisseurs, factures non parvenues'],
            ['DH', '408100', 'Fournisseurs'],
            ['DH', '408300', 'Fournisseurs sous-traitants'],
            ['DH', '408600', 'Fournisseurs, intérêts courus'],
            
            ['BC', '401000', 'Fournisseurs, dettes en compte'],
            ['BC', '401100', 'Fournisseurs'],
            ['BC', '401300', 'Fournisseurs sous-traitants'],
            ['BC', '401600', 'Fournisseurs, réserve de propriété'],
            ['BC', '401700', 'Fournisseurs, retenues de garantie'],
            ['BC', '402000', 'Fournisseurs, effets à payer'],
            ['BC', '402100', 'Fournisseurs, effets à payer'],
            ['BC', '402300', 'Fournisseurs sous-traitants, effets à payer'],
            ['BC', '408000', 'Fournisseurs, factures non parvenues'],
            ['BC', '408100', 'Fournisseurs'],
            ['BC', '408300', 'Fournisseurs sous-traitants'],
            ['BC', '408600', 'Fournisseurs, intérêts courus'],
            ['BC', '409000', 'Fournisseurs débiteurs'],
            ['BC', '409100', 'Fournisseurs avances et acomptes versés'],
            ['BC', '409300', 'Fournisseurs sous-traitants avances et acomptes versés'],
            ['BC', '409400', 'Fournisseurs créances pour emballages et matériels à rendre'],
            ['BC', '409800', 'Fournisseurs, rabais, remises, ristournes et autres avoirs à obtenir'],
            
            ['BD', '411000', 'Adhérents'],
            ['BD', '412000', 'Clients-usagers'],
            ['BD', '413000', 'Adhérents, Clients-usagers, chèques, effets et autres valeurs impayés'],
            ['BD', '413100', 'Adhérents, chèques impayés'],
            ['BD', '413200', 'Clients-usagers, chèques impayés'],
            ['BD', '413300', 'Adhérents, Autres valeurs impayées'],
            ['BD', '413800', 'Clients-usagers, autres valeurs impayées'],
            ['BD', '416000', 'Créances, adhérents, clients-usagers litigieuses ou douteuses'],
            ['BD', '416100', 'Adhérents cotisations litigieuses ou douteuses'],
            ['BD', '416200', 'Créances litigieuses ou douteuses'],
            ['BD', '418000', 'Adhérents, clients-usagers produits à recevoir'],
            ['BD', '418100', 'Adhérents, appels de fonds à établir'],
            ['BD', '418200', 'Clients- usagers, factures à établir'],
            ['BD', '418600', 'Adhérents, Clients-usagers, intérêts courus'],
            
            ['BE', '421000', 'Personnel, avances et acomptes'],
            ['BE', '421100', 'Personnel, avances'],
            ['BE', '421200', 'Personnel, acomptes'],
            ['BE', '421300', 'Frais avancés et fournitures au personnel'],
            
            ['DG', '419000', 'Adhérents, Clients-usagers créditeurs'],
            ['DG', '419100', 'Adhérents, avances reçues'],
            ['DG', '419200', 'Clients-usagers, avances et acomptes reçus'],
            ['DG', '419400', 'Clients-usagers, dettes pour emballages et matériels consignés'],
            ['DG', '419800', 'Clients-usagers, rabais, remises, ristournes et autres avoirs à accorder'],
            ['DG', '411000', 'Adhérents'],
            ['DG', '412000', 'Clients-usagers'],
            ['DG', '413000', 'Adhérents, Clients-usagers, chèques, effets et autres valeurs impayés'],
            ['DG', '413100', 'Adhérents, chèques impayés'],
            ['DG', '413200', 'Clients-usagers, chèques impayés'],
            ['DG', '413300', 'Adhérents, Autres valeurs impayées'],
            ['DG', '413800', 'Clients-usagers, autres valeurs impayées'],
            ['DG', '416000', 'Créances, adhérents, clients-usagers litigieuses ou douteuses'],
            ['DG', '416100', 'Adhérents cotisations litigieuses ou douteuses'],
            ['DG', '416200', 'Créances litigieuses ou douteuses'],
            ['DG', '418000', 'Adhérents, clients-usagers produits à recevoir'],
            ['DG', '418100', 'Adhérents, appels de fonds à établir'],
            ['DG', '418200', 'Clients- usagers, factures à établir'],
            ['DG', '418600', 'Adhérents, Clients-usagers, intérêts courus'],
            
            ['DI', '421000', 'Personnel, avances et acomptes'],
            ['DI', '421100', 'Personnel, avances'],
            ['DI', '421200', 'Personnel, acomptes'],
            ['DI', '421300', 'Frais avancés et fournitures au personnel'],
            ['DI', '422000', 'Personnel, rémunérations dues'],
            ['DI', '423000', 'Personnel, oppositions, saisies arrêts'],
            ['DI', '423100', 'Personnel, oppositions'],
            ['DI', '423200', 'Personnel, saisies arrêts'],
            ['DI', '423300', 'Personnel, avis à tiers détenteur'],
            ['DI', '424000', 'Personnel, œuvres sociales internes'],
            ['DI', '424100', 'Assistance médicale'],
            ['DI', '424200', 'Allocations familiales'],
            ['DI', '424500', 'Organismes sociaux rattachés à l\'entité'],
            ['DI', '424800', 'Autres œuvres sociales internes'],
            ['DI', '425000', 'Représentants du personnel'],
            ['DI', '425100', 'Délégués du personnel'],
            ['DI', '425200', 'Syndicats et assimilés'],
            ['DI', '425800', 'Autres représentants du personnel'],
            ['DI', '427000', 'Personnel – dépôts'],
            ['DI', '428000', 'Personnel, charges à payer et produits à recevoir'],
            ['DI', '428100', 'Personnel congés à payer'],
            ['DI', '428600', 'Autres Charges à payer'],
            ['DI', '428700', 'Produits à recevoir'],
            ['DI', '431000', 'Sécurité sociale'],
            ['DI', '431100', 'Prestations familiales'],
            ['DI', '431200', 'Accidents de travail'],
            ['DI', '431800', 'Autres cotisations sociales'],
            ['DI', '432000', 'Caisses de retraite'],
            ['DI', '432100', 'Caisse de retraite obligatoire'],
            ['DI', '432200', 'Caisse de retraite complémentaire'],
            ['DI', '432800', 'Autres caisses de retraites'],
            ['DI', '433000', 'Autres organismes sociaux'],
            ['DI', '433100', 'Mutuelle de santé'],
            ['DI', '433200', 'Assurances retraite'],
            ['DI', '433300', 'Assurances et organismes de santé'],
            ['DI', '438000', 'Organismes sociaux, charges à payer et produits à recevoir'],
            ['DI', '438100', 'Charges sociales sur gratifications à payer'],
            ['DI', '438200', 'Charges sociales sur congés à payer'],
            ['DI', '438600', 'Autres charges à payer'],
            ['DI', '438700', 'Produits à recevoir'],
            ['DI', '442000', 'État, autres impôts et taxes'],
            ['DI', '442100', 'Impôts et taxes d\'Etat'],
            ['DI', '442200', 'Impôts et taxes pour les collectivités publiques'],
            ['DI', '442300', 'Impôts et taxes recouvrables sur des obligataires'],
            ['DI', '442400', 'Impôts et taxes recouvrables sur des adhérents et autres'],
            ['DI', '442600', 'Droits de douane'],
            ['DI', '442800', 'Autres impôts et taxes'],
            ['DI', '443000', 'État, T.V.A. Facturée'],
            ['DI', '444000', 'État, T.V.A. due ou crédit de T.V.A.'],
            ['DI', '445000', 'État, T.V.A. Récupérable'],
            ['DI', '446000', 'État, autres taxes sur le chiffre d\'affaires'],
            ['DI', '447000', 'État, impôts retenus à la source'],
            ['DI', '447100', 'Impôt général sur le revenu'],
            ['DI', '447200', 'Impôts sur salaires'],
            ['DI', '447300', 'Contribution nationale'],
            ['DI', '447400', 'Contribution nationale de solidarité'],
            ['DI', '447800', 'Autres impôts et contributions'],
            ['DI', '448000', 'État, charges à payer et produits à recevoir'],
            ['DI', '448600', 'Charges à payer'],
            ['DI', '448700', 'Produits à recevoir'],
            ['DI', '449000', 'État, créances et dettes diverses'],
            ['DI', '449100', 'Etat, Subvention à recevoir'],
            ['DI', '451000', 'Associations et assimilées'],
            ['DI', '451100', 'Apporteurs en nature'],
            ['DI', '451200', 'Apporteurs en numéraire'],
            ['DI', '451500', 'Adhérents, dirigeants, comptes courants'],
            ['DI', '452000', 'Fondations et assimilées'],
            ['DI', '452100', 'Apporteurs en nature'],
            ['DI', '452200', 'Apporteurs en numéraire'],
            ['DI', '452500', 'Fondateurs, dirigeants, comptes courants'],
            ['DI', '453000', 'Ordres professionnels'],
            ['DI', '453100', 'Apporteurs en nature'],
            ['DI', '453200', 'Apporteurs en numéraire'],
            ['DI', '453500', 'Membres, dirigeants, comptes courants'],
            ['DI', '454000', 'Organisations politiques'],
            ['DI', '454100', 'Apporteurs en nature'],
            ['DI', '454200', 'Apporteurs en numéraire'],
            ['DI', '454500', 'Adhérents, dirigeants, comptes courants'],
            ['DI', '455000', 'Organisations syndicales'],
            ['DI', '455100', 'Apporteurs en nature'],
            ['DI', '455200', 'Apporteurs en numéraire'],
            ['DI', '455500', 'Adhérents, dirigeants, comptes courants'],
            ['DI', '456000', 'Organisations religieuses, apporteurs'],
            ['DI', '456100', 'Congrégations religieuses et assimilées'],
            ['DI', '456200', 'Waqf et assimilés'],
            ['DI', '457000', 'Mécènes, bénévoles et assimilés'],
            ['DI', '457100', 'Mécènes et assimilés'],
            ['DI', '457200', 'Bénévoles et assimilés'],
            ['DI', '458000', 'Autres fondateurs et apporteurs'],
            ['DI', '462000', 'Bailleurs - projet de développement, Fonds d\'administration'],
            ['DI', '463000', 'Etat - projet de développement, Fonds d\'administration'],
            ['DI', '464000', 'Autres organismes de financement assimilés - projet de développement, Fonds d\'administration'],
            ['DI', '469000', 'Fonds d\'administration affectés aux charges'],
            ['DI', '469200', 'Fonds d\'administration affectés aux charges – Bailleurs'],
            ['DI', '469300', 'Fonds d\'administration affectés aux charges - Etat'],
            ['DI', '469400', 'Fonds d\'administration affectés aux charges - Autres organismes de financement'],
            ['DI', '471000', 'Débiteurs et créditeurs divers'],
            ['DI', '471100', 'Débiteurs divers'],
            ['DI', '471200', 'Créditeurs divers'],
            ['DI', '471300', 'Créditeurs, dons en nature courants non consommés'],
            ['DI', '471700', 'Débiteurs divers - retenues de garantie'],
            ['DI', '471900', 'Bons de souscription d\'actions et d\'obligations'],
            ['DI', '472000', 'Créances et dettes sur titres de placement'],
            ['DI', '472100', 'Créances sur cessions de titres de placement'],
            ['DI', '472600', 'Versements restant à effectuer sur titres de placement non libérés'],
            ['DI', '473000', 'État, collectivités publiques et autres organismes assimilés – subventions à recevoir'],
            ['DI', '473100', 'Subventions d\'investissement à recevoir'],
            ['DI', '473200', 'Subventions d\'exploitation à recevoir'],
            ['DI', '473300', 'Subventions d\'équilibre à recevoir'],
            ['DI', '473800', 'Autres subventions à recevoir'],
            ['DI', '473900', 'Subventions à reverser'],
            ['DI', '474000', 'Compte de répartition périodique des charges et des produits'],
            ['DI', '474600', 'Compte de répartition périodique des charges'],
            ['DI', '474700', 'Compte de répartition périodique des produits'],
            ['DI', '475000', 'Générosités financières à recevoir'],
            ['DI', '476000', 'Charges constatées d\'avance'],
            ['DI', '477000', 'Produits constatés d\'avance'],
            ['DI', '499000', 'Provisions pour risques et charges à court terme'],
            ['DI', '499100', 'Provisions pour risques sur opérations d\'exploitation'],
            ['DI', '599000', 'Provisions pour risque et charges à court terme à caractère financier'],
            
            ['DF', '481000', 'Fournisseurs d\'investissements'],
            ['DF', '481100', 'Fournisseurs, immobilisations incorporelles'],
            ['DF', '481200', 'Fournisseurs, immobilisations corporelles'],
            ['DF', '481300', 'Versements restant à effectuer sur titres de participation et titres immobilisés non libérés'],
            ['DF', '481600', 'Fournisseurs, réserve de propriété - immobilisations'],
            ['DF', '481610', 'Fournisseurs, réserve de propriété – immobilisations incorporelles'],
            ['DF', '481620', 'Fournisseurs, réserve de propriété – immobilisations corporelles'],
            ['DF', '481700', 'Fournisseurs, retenues de garantie- immobilisations'],
            ['DF', '481710', 'Fournisseurs, retenues de garantie – immobilisations incorporelles'],
            ['DF', '481720', 'Fournisseurs, retenues de garantie – immobilisations corporelles'],
            ['DF', '481800', 'Fournisseurs, factures non parvenues - immobilisations'],
            ['DF', '481810', 'Fournisseurs, factures non parvenues – immobilisations incorporelles'],
            ['DF', '481820', 'Fournisseurs, factures non parvenues – immobilisations corporelles'],
            ['DF', '484000', 'Autres dettes hors activités ordinaires (H.A.O.)'],
            ['DF', '486100', 'Dettes des dons et legs d\'immobilisations'],
            ['DF', '488000', 'Créditeurs, dons en nature HAO non consommés'],
            ['DF', '488100', 'Créditeurs, dons en nature HAO non consommés'],
            ['DF', '499800', 'Provisions pour risques sur opérations H.A.O.'],
            
            ['BA', '485000', 'Créances sur cessions d\'immobilisations'],
            ['BA', '485100', 'Créances, en compte, immobilisations incorporelles'],
            ['BA', '485200', 'Créances, en compte, immobilisations corporelles'],
            ['BA', '485600', 'Créances, immobilisations financières'],
            ['BA', '485700', 'Créances, Retenues de garantie sur cession immobilisations'],
            ['BA', '485800', 'Créances sur cession d\'immobilisations, factures à établir'],
            ['BA', '486500', 'Créances reçues sur dons et legs d\'immobilisations'],
            
            ['BC', '490000', 'Dépréciations des comptes fournisseurs'],
            
            ['BD', '491000', 'Dépréciations des comptes adhérents et clients-usagers'],
            ['BD', '491100', 'Dépréciations des créances litigieuses'],
            ['BD', '491200', 'Dépréciations des créances douteuses'],
            
            ['BE', '492000', 'Dépréciations des comptes personnel'],
            ['BE', '493000', 'Dépréciations des comptes organismes sociaux'],
            ['BE', '494000', 'Dépréciations des comptes État et Collectivités publiques'],
            ['BE', '497000', 'Dépréciations des comptes débiteurs divers'],
            
            ['BA', '498000', 'Dépréciations des comptes de créances H.A.O.'],
            ['BA', '498500', 'Dépréciations des créances sur cessions d\'immobilisations'],
            ['BA', '498800', 'Dépréciations des autres créances H.A.O.'],
            
            // TRESORERIE
            ['BU', '501000', 'Titres du trésor et bons de caisse à court terme'],
            ['BU', '501100', 'Titres du Trésor à court terme'],
            ['BU', '501200', 'Titres d\'organismes financiers'],
            ['BU', '501300', 'Bons de caisse à court terme'],
            ['BU', '501600', 'Frais d\'acquisition des titres de trésor et bons de caisse'],
            ['BU', '502000', 'Actions'],
            ['BU', '502200', 'Actions cotées'],
            ['BU', '502300', 'Actions non cotées'],
            ['BU', '502500', 'Autres actions'],
            ['BU', '502600', 'Frais d\'acquisition des actions'],
            ['BU', '503000', 'Obligations'],
            ['BU', '503200', 'Obligations cotées'],
            ['BU', '503300', 'Obligations non cotées'],
            ['BU', '503500', 'Autres obligations'],
            ['BU', '503600', 'Frais d\'acquisition des obligations'],
            ['BU', '504000', 'Bons de souscription'],
            ['BU', '504200', 'Bons de souscription d\'actions'],
            ['BU', '504300', 'Bons de souscription d\'obligations'],
            ['BU', '505000', 'Titres négociables hors Région'],
            ['BU', '506000', 'Intérêts courus'],
            ['BU', '506100', 'Titres du Trésor et bons de caisse à court terme'],
            ['BU', '506200', 'Actions'],
            ['BU', '506300', 'Obligations'],
            ['BU', '508000', 'Autres titres de placement et créances assimilées'],
            
            ['BV', '513000', 'Chèques à encaisser'],
            ['BV', '514000', 'Chèques à l\'encaissement'],
            ['BV', '515000', 'Cartes de crédit à encaisser'],
            ['BV', '518000', 'Autres valeurs à l\'encaissement'],
            ['BV', '518500', 'Chèques de voyage'],
            ['BV', '518600', 'Coupons échus'],
            ['BV', '518700', 'Intérêts échus des obligations'],
            
            ['BW', '521000', 'Banques locales'],
            ['BW', '521100', 'Banques en monnaie nationale'],
            ['BW', '521500', 'Banques en devises'],
            ['BW', '522000', 'Banques autres États Région'],
            ['BW', '523000', 'Banques autres États zone monétaire'],
            ['BW', '524000', 'Banques hors zone monétaire'],
            ['BW', '525000', 'Banques dépôt à terme et opérations assimilées'],
            ['BW', '526000', 'Banques, intérêts courus'],
            ['BW', '526100', 'Banque, intérêts courus charges à payer'],
            ['BW', '526700', 'Banque, intérêts courus produits à recevoir'],
            ['BW', '531000', 'Banques postales'],
            ['BW', '532000', 'Trésor'],
            ['BW', '533000', 'Sociétés de gestion et d\'intermédiation (S.G.I.)'],
            ['BW', '536000', 'Établissements financiers, intérêts courus'],
            ['BW', '536100', 'Établissements financiers, intérêts courus charges à payer'],
            ['BW', '536700', 'Établissements financiers, intérêts courus produits à recevoir'],
            ['BW', '538000', 'Autres organismes financiers'],
            ['BW', '551000', 'Monnaie électronique - carte carburant'],
            ['BW', '552000', 'Monnaie électronique - téléphone portable'],
            ['BW', '553000', 'Monnaie électronique - carte péage'],
            ['BW', '554000', 'Porte-monnaie électronique'],
            ['BW', '558000', 'Autres instruments de monnaie électronique'],
            ['BW', '571000', 'Caisse en monnaie nationale'],
            ['BW', '572000', 'Caisse en devises'],
            ['BW', '585000', 'Virements de fonds'],
            ['BW', '588000', 'Autres virements internes'],
            
            ['DW', '561000', 'Crédits de trésorerie'],
            ['DW', '565000', 'Escompte de crédits ordinaires'],
            ['DW', '566000', 'Banques, crédits de trésorerie, intérêts courus'],
            ['DW', '521000', 'Banques locales'],
            ['DW', '521100', 'Banques en monnaie nationale'],
            ['DW', '521500', 'Banques en devises'],
            ['DW', '522000', 'Banques autres États Région'],
            ['DW', '523000', 'Banques autres États zone monétaire'],
            ['DW', '524000', 'Banques hors zone monétaire'],
            ['DW', '525000', 'Banques dépôt à terme et opérations assimilées'],
            ['DW', '526000', 'Banques, intérêts courus'],
            ['DW', '526100', 'Banque, intérêts courus charges à payer'],
            ['DW', '526700', 'Banque, intérêts courus produits à recevoir'],
            ['DW', '531000', 'Banques postales'],
            ['DW', '532000', 'Trésor'],
            ['DW', '533000', 'Sociétés de gestion et d\'intermédiation (S.G.I.)'],
            ['DW', '536000', 'Établissements financiers, intérêts courus'],
            ['DW', '536100', 'Établissements financiers, intérêts courus charges à payer'],
            ['DW', '536700', 'Établissements financiers, intérêts courus produits à recevoir'],
            ['DW', '538000', 'Autres organismes financiers'],
            ['DW', '551000', 'Monnaie électronique - carte carburant'],
            ['DW', '552000', 'Monnaie électronique - téléphone portable'],
            ['DW', '553000', 'Monnaie électronique - carte péage'],
            ['DW', '554000', 'Porte-monnaie électronique'],
            ['DW', '558000', 'Autres instruments de monnaie électronique'],
            ['DW', '571000', 'Caisse en monnaie nationale'],
            ['DW', '572000', 'Caisse en devises'],
            ['DW', '585000', 'Virements de fonds'],
            ['DW', '588000', 'Autres virements internes'],
            
            ['BU', '590000', 'Dépréciations des titres de placement'],
            
            ['BV', '591000', 'Dépréciations des titres et valeurs à encaisser'],
            
            ['BW', '592000', 'Dépréciations des comptes banques'],
            ['BW', '593000', 'Dépréciations des comptes établissements financiers et assimilés'],
            ['BW', '595000', 'Dépréciations des comptes d\'instruments de monnaie électronique'],
            
            ['BY', '478000', 'Écarts de conversion - actif'],
            ['BY', '478100', 'Diminution des créances d\'exploitation et HAO'],
            ['BY', '478110', 'Diminution des créances d\'exploitation'],
            ['BY', '478180', 'Diminution des créances HAO'],
            ['BY', '478200', 'Diminution des créances financières'],
            ['BY', '478300', 'Augmentation des dettes d\'exploitation et HAO'],
            ['BY', '478310', 'Augmentation des dettes d\'exploitation'],
            ['BY', '478380', 'Augmentation des dettes HAO'],
            ['BY', '478400', 'Augmentation des dettes financières'],
            ['BY', '478600', 'Différences d\'évaluation sur instruments de trésorerie'],
            ['BY', '478800', 'Différences compensées par couverture de change'],
            
            ['DY', '479000', 'Écarts de conversion – passif'],
            ['DY', '479100', 'Augmentation des créances d\'exploitation et HAO'],
            ['DY', '479110', 'Augmentation des créances d\'exploitation'],
            ['DY', '479180', 'Augmentation des créances HAO'],
            ['DY', '479200', 'Augmentation des créances financières'],
            ['DY', '479300', 'Diminution des dettes d\'exploitation et HAO'],
            ['DY', '479310', 'Diminution des dettes d\'exploitation'],
            ['DY', '479380', 'Diminution des dettes HAO'],
            ['DY', '479400', 'Diminution des dettes financières'],
            ['DY', '479700', 'Différences d\'évaluation sur instruments de trésorerie'],
            ['DY', '479800', 'Différences compensées par couverture de change'],
            
            // COMPTES DE GESTION (6 et 7) - pour le compte de résultat
            ['TA', '601000', 'Achats de biens et services liés à l\'activité'],
            ['TA', '601100', 'Achats de biens et services liés à l\'activité dans l\'Etat partie'],
            ['TA', '601200', 'Achats de biens et services liés à l\'activité dans la Région'],
            ['TA', '601300', 'Achats de biens et services liés à l\'activité hors Région'],
            ['TA', '601500', 'frais sur achats (2) de biens et services liés à l\'activité'],
            ['TA', '601900', 'Rabais, Remises et Ristournes obtenus (non ventilés)'],
            
            ['TB', '603100', 'Variations des stocks de biens et services liés à l\'activité'],
            
            ['TC', '602000', 'Achats de marchandises, de matières premières et fournitures liées'],
            ['TC', '602100', 'Achats de marchandises et matières premières dans l\'Etat partie'],
            ['TC', '602200', 'Achats de marchandises et matières premières dans la Région'],
            ['TC', '602300', 'Achats de marchandises et matières premières hors Région'],
            ['TC', '602500', 'frais sur achats de marchandises et matières ( 2 )'],
            ['TC', '602900', 'Rabais, Remises et Ristournes obtenus (non ventilés)'],
            
            ['TD', '604000', 'Achats stockés de matières et fournitures consommables'],
            ['TD', '604100', 'Matières consommables'],
            ['TD', '604200', 'Matières combustibles'],
            ['TD', '604300', 'Produits d\'entretien'],
            ['TD', '604500', 'Frais sur achats (2) matières et fournitures consommables'],
            ['TD', '604600', 'Fournitures de magasin'],
            ['TD', '604700', 'Fournitures de bureau'],
            ['TD', '604900', 'Rabais, Remises et Ristournes obtenus (non ventilés)'],
            ['TD', '605000', 'Autres achats'],
            ['TD', '605100', 'Fournitures non stockables -Eau'],
            ['TD', '605200', 'Fournitures non stockables - Électricité'],
            ['TD', '605300', 'Fournitures non stockables – Autres énergies'],
            ['TD', '605400', 'Fournitures d\'entretien non stockables'],
            ['TD', '605500', 'Fournitures de bureau non stockables'],
            ['TD', '605600', 'Achats de petit matériel et outillage'],
            ['TD', '605700', 'Achats d\'études et prestations de services'],
            ['TD', '605800', 'Achats de travaux, matériels et équipements'],
            ['TD', '605900', 'Rabais, Remises et Ristournes obtenus (non ventilés)'],
            ['TD', '606000', 'Achats autres activités'],
            ['TD', '606100', 'Billetteries'],
            ['TD', '606200', 'Tombola et autres jeux'],
            ['TD', '606300', 'Bons d\'achats'],
            ['TD', '606400', 'Voyages et sorties'],
            ['TD', '606800', 'Autres activités'],
            ['TD', '608000', 'Achats d\'emballages'],
            ['TD', '608100', 'Emballages perdus'],
            ['TD', '608200', 'Emballages récupérables non identifiables'],
            ['TD', '608300', 'Emballages à usage mixte'],
            ['TD', '608500', 'Frais sur achats (2)d\'emballages'],
            ['TD', '608900', 'Rabais, Remises et Ristournes obtenus (non ventilés)'],
            
            ['TE', '603200', 'Variations des stocks de marchandises'],
            ['TE', '603300', 'Variations des stocks de matières premières et fournitures liées'],
            ['TE', '603400', 'Variations des stocks d\'autres approvisionnements'],
            ['TE', '603500', 'Variations de stocks de dons en nature à distribuer'],
            
            ['TF', '612000', 'Transports sur ventes'],
            ['TF', '613000', 'Transports pour le compte de tiers'],
            ['TF', '614000', 'Transports du personnel'],
            ['TF', '616000', 'Transports de plis'],
            ['TF', '618000', 'Autres frais de transport'],
            ['TF', '618100', 'Voyages et déplacements'],
            ['TF', '618300', 'Transports administratifs'],
            ['TF', '619000', 'Rabais, Remises et Ristournes Obtenus (non ventilés)'],
            
            ['TG', '621000', 'Sous-traitance générale'],
            ['TG', '622000', 'Locations, charges locatives'],
            ['TG', '622100', 'Locations de terrains'],
            ['TG', '622200', 'Locations de bâtiments'],
            ['TG', '622300', 'Locations de matériels et outillages'],
            ['TG', '622400', 'Malis sur emballages'],
            ['TG', '622500', 'Locations d\'emballages'],
            ['TG', '622600', 'Fermages et loyers du foncier'],
            ['TG', '622800', 'Locations et charges locatives diverses'],
            ['TG', '623000', 'Redevances de location-acquisition'],
            ['TG', '623200', 'Crédit-bail immobilier'],
            ['TG', '623300', 'Crédit-bail mobilier'],
            ['TG', '623400', 'Location-vente'],
            ['TG', '623800', 'Autres contrats de location-acquisition'],
            ['TG', '624000', 'Entretien, réparation, remise en état et maintenance'],
            ['TG', '624100', 'Entretien et réparation des biens immobiliers'],
            ['TG', '624200', 'Entretien et réparation des biens mobiliers'],
            ['TG', '624300', 'Maintenance'],
            ['TG', '624800', 'Autres entretiens et réparation'],
            ['TG', '625000', 'Primes d\'assurance'],
            ['TG', '625100', 'Assurances multirisques'],
            ['TG', '625200', 'Assurances matériel de transport'],
            ['TG', '625300', 'Assurances risques d\'exploitation'],
            ['TG', '625800', 'Autres primes d\'assurances'],
            ['TG', '626000', 'Études, recherches et documentation'],
            ['TG', '626100', 'Études et recherches'],
            ['TG', '626500', 'Documentation générale'],
            ['TG', '626600', 'Documentation technique'],
            ['TG', '627000', 'Publicité, publications, relations publiques'],
            ['TG', '627100', 'Annonces, insertions'],
            ['TG', '627200', 'Catalogues, imprimés publicitaires'],
            ['TG', '627300', 'Congrès, universités et assimilés'],
            ['TG', '627400', 'Manifestations'],
            ['TG', '627500', 'Publications'],
            ['TG', '627700', 'Frais de colloques, séminaires, conférences'],
            ['TG', '627800', 'Autres charges de publicité et relations publiques'],
            ['TG', '628000', 'Frais de télécommunications'],
            ['TG', '628100', 'Frais de téléphone'],
            ['TG', '628300', 'Frais de télécopie'],
            ['TG', '628400', 'Frais d\'internet'],
            ['TG', '628800', 'Autres frais de télécommunications'],
            
            ['TH', '641000', 'Impôts et taxes directs'],
            ['TH', '641100', 'Impôts fonciers et taxes annexes'],
            ['TH', '641200', 'Licences et taxes annexes'],
            ['TH', '641300', 'Taxes sur appointements et salaires'],
            ['TH', '641400', 'Taxes d\'apprentissage'],
            ['TH', '641500', 'Formation professionnelle continue'],
            ['TH', '641600', 'Patente ou contribution économique locale'],
            ['TH', '641800', 'Autres impôts et taxes directs'],
            ['TH', '645000', 'Impôts et taxes indirects'],
            ['TH', '646000', 'Droits d\'enregistrement'],
            ['TH', '646100', 'Droits de mutation'],
            ['TH', '646200', 'Droits de timbre'],
            ['TH', '646400', 'Vignettes'],
            ['TH', '646800', 'Autres droits d\'enregistrement'],
            ['TH', '647000', 'Pénalités, amendes fiscales'],
            ['TH', '647100', 'Pénalités d\'assiette, impôts directs'],
            ['TH', '647200', 'Pénalités d\'assiette, impôts indirects'],
            ['TH', '647300', 'Pénalités de recouvrement, impôts directs'],
            ['TH', '647400', 'Pénalités de recouvrement, impôts indirects'],
            ['TH', '647800', 'Autres pénalités et amendes fiscales'],
            ['TH', '648000', 'Autres impôts et taxes'],
            ['TH', '649000', 'Dégrèvements et annulations des impôts et taxes'],
            
            ['TI', '651000', 'Pertes sur créances adhérents clients, et autres débiteurs'],
            ['TI', '651100', 'Clients-usagers'],
            ['TI', '651200', 'Adhérents'],
            ['TI', '651500', 'Autres débiteurs'],
            ['TI', '652000', 'Subventions versées par l\'entité'],
            ['TI', '654000', 'Dons en nature courants à distribuer'],
            ['TI', '654100', 'Dons en nature courants à distribuer non affectés'],
            ['TI', '654500', 'Dons en nature courants à distribuer affectés'],
            ['TI', '657000', 'Pénalités et amendes pénales'],
            ['TI', '658000', 'Charges diverses'],
            ['TI', '659000', 'Charges pour dépréciations et provisions pour risques à court terme d\'exploitation'],
            ['TI', '659100', 'Provisions sur risques à court terme'],
            ['TI', '659300', 'Charges pour dépréciations sur stocks'],
            ['TI', '659400', 'Charges pour dépréciations sur créances'],
            ['TI', '659800', 'Autres charges pour dépréciations et provisions pour risques à court terme'],
            
            ['TJ', '661000', 'Rémunérations directes versées au personnel national'],
            ['TJ', '661100', 'Appointements salaires et commissions'],
            ['TJ', '661200', 'Primes et gratifications'],
            ['TJ', '661300', 'Congés payés'],
            ['TJ', '661400', 'Indemnités de préavis et de licenciement'],
            ['TJ', '661500', 'Indemnités de maladie versées aux travailleurs'],
            ['TJ', '661600', 'Supplément familial'],
            ['TJ', '661700', 'Avantages en nature'],
            ['TJ', '661800', 'Autres rémunérations directes'],
            ['TJ', '662000', 'Rémunérations directes versées au personnel non national'],
            ['TJ', '662100', 'Appointements salaires et commissions'],
            ['TJ', '662200', 'Primes et gratifications'],
            ['TJ', '662300', 'Congés payés'],
            ['TJ', '662400', 'Indemnités de préavis et de licenciement'],
            ['TJ', '662500', 'Indemnités de maladie versées aux travailleurs'],
            ['TJ', '662600', 'Supplément familial'],
            ['TJ', '662700', 'Avantages en nature'],
            ['TJ', '662800', 'Autres rémunérations directes'],
            ['TJ', '663000', 'Indemnités forfaitaires versées au personnel'],
            ['TJ', '663100', 'Indemnités de logement'],
            ['TJ', '663200', 'Indemnités de représentation'],
            ['TJ', '663300', 'Indemnités d\'expatriation'],
            ['TJ', '663400', 'Indemnités de transport'],
            ['TJ', '663800', 'Autres indemnités et avantages divers'],
            ['TJ', '664000', 'Charges sociales'],
            ['TJ', '664100', 'Charges sociales sur rémunération du personnel national'],
            ['TJ', '664200', 'Charges sociales sur rémunération du personnel non national'],
            ['TJ', '665000', 'Habillement et équipement du personnel'],
            ['TJ', '667000', 'Rémunération transférée de personnel extérieur'],
            ['TJ', '667100', 'Personnel intérimaire'],
            ['TJ', '667200', 'Personnel détaché ou prêté à l\'entité'],
            ['TJ', '668000', 'Autres charges sociales'],
            ['TJ', '668100', 'Versements aux syndicats et assimilés'],
            ['TJ', '668200', 'Versements aux comités d\'hygiène et de sécurité'],
            ['TJ', '668300', 'Versements et contributions aux autres œuvres sociales'],
            ['TJ', '668400', 'Médecine du travail et pharmacie'],
            ['TJ', '668500', 'Assurances et organismes de santé'],
            ['TJ', '668600', 'Assurances retraite et fonds de pensions'],
            ['TJ', '668700', 'Majorations et pénalités sociales'],
            ['TJ', '668800', 'Charges sociales diverses'],
            ['TJ', '669000', 'Dégrèvements et annulations des charges sociales'],
            
            ['TK', '671000', 'Intérêts des emprunts'],
            ['TK', '671100', 'Emprunts obligataires'],
            ['TK', '671200', 'Emprunts auprès des établissements de crédit'],
            ['TK', '672000', 'Intérêts dans loyers de location-acquisition'],
            ['TK', '672100', 'Intérêts dans loyers de location-acquisition/crédit-bail immobilier'],
            ['TK', '672200', 'Intérêts dans loyers de location-acquisition/crédit-bail mobilier'],
            ['TK', '672300', 'Intérêts dans loyers de location-acquisition/location-vente'],
            ['TK', '672400', 'Intérêts dans loyers des autres locations-acquisition'],
            ['TK', '673000', 'Escomptes accordés'],
            ['TK', '674000', 'Autres intérêts'],
            ['TK', '674100', 'Avances reçues et dépôts créditeurs'],
            ['TK', '674200', 'Comptes courants bloqués'],
            ['TK', '674400', 'Intérêts sur dettes commerciales'],
            ['TK', '674500', 'Intérêts bancaires et sur opérations de financement (escompte…)'],
            ['TK', '674800', 'Intérêts sur dettes diverses'],
            ['TK', '676000', 'Pertes de change financières'],
            ['TK', '677000', 'Pertes sur titres de placement'],
            ['TK', '677100', 'Pertes sur cessions de titres de placement'],
            ['TK', '678000', 'Pertes et charges sur risques financiers'],
            ['TK', '678100', 'sur rentes viagères'],
            ['TK', '678200', 'sur opérations financières'],
            ['TK', '679000', 'Charges pour dépréciations et provisions pour risques à court terme financières'],
            ['TK', '679100', 'sur risques financiers'],
            ['TK', '679500', 'sur titres de placement'],
            ['TK', '679800', 'Autres charges pour dépréciations et provisions pour risques à court terme financières'],
            
            ['TL', '680000', 'Dotations aux amortissements d\'usufruit temporaire'],
            ['TL', '681000', 'Dotations aux amortissements d\'exploitation'],
            ['TL', '681200', 'Dotations aux amortissements des immobilisations incorporelles'],
            ['TL', '681300', 'Dotations aux amortissements des immobilisations corporelles'],
            
            ['TN', '811000', 'Valeurs comptables des cessions d\'immobilisations incorporelles'],
            ['TN', '812000', 'Valeurs comptables des cessions d\'immobilisations corporelles'],
            ['TN', '816000', 'Valeurs comptables des cessions d\'immobilisations financières'],
            ['TN', '818000', 'Valeurs comptables des cessions d\'immobilisations reçues destinées à la vente provenant de dons et legs'],
            ['TN', '831000', 'Charges H.A.O. constatées'],
            ['TN', '831100', 'Charges sur donations et legs'],
            ['TN', '832000', 'Dons en nature H.A.O. à distribuer'],
            ['TN', '832100', 'Dons en nature H.A.O. non affectés'],
            ['TN', '832500', 'Dons en nature H.A.O. affectés'],
            ['TN', '834000', 'Pertes sur créances H.A.O.'],
            ['TN', '836000', 'Abandons de créances consentis'],
            ['TN', '838000', 'Transferts de charges H.A.O.'],
            ['TN', '839000', 'Charges pour dépréciations et provisions pour risques à court terme H.A.O.'],
            ['TN', '851000', 'Dotations aux provisions réglementées'],
            ['TN', '852000', 'Dotations aux amortissements H.A.O.'],
            ['TN', '853000', 'Dotations aux dépréciations H.A.O.'],
            ['TN', '854000', 'Dotations aux provisions pour risques et charges H.A.O.'],
            ['TN', '858000', 'Autres dotations H.A.O'],
            
            ['RA', '701000', 'Cotisations des adhérents'],
            ['RA', '702000', 'Quote-part de fonds d\'administration transférés'],
            
            ['RB', '703000', 'Quote-part de dotation consomptible transférée'],
            
            ['RC', '704000', 'Revenus liés à la générosité'],
            ['RC', '704100', 'Dons'],
            ['RC', '704200', 'Legs'],
            ['RC', '704300', 'Deniers du culte'],
            ['RC', '704400', 'Zakat, Dîme, quête et assimilées'],
            ['RC', '704500', 'Célébrations'],
            ['RC', '704600', 'Mécénats'],
            ['RC', '704700', 'Parrainage'],
            ['RC', '704800', 'Autres revenus liés à la générosité'],
            
            ['RD', '705100', 'Ventes marchandises'],
            
            ['RE', '705200', 'Services vendus'],
            ['RE', '705300', 'Ventes de produits finis'],
            
            ['RF', '711000', 'Subventions d\'exploitation versées par l\'État et les Collectivités publiques'],
            ['RF', '712000', 'Subventions d\'exploitation versées par les bailleurs de fonds des projets et assimilés'],
            ['RF', '713000', 'Subventions d\'exploitation versées par les organismes internationaux'],
            ['RF', '718000', 'Autres subventions d\'exploitation'],
            
            ['RG', '706000', 'Revenus des manifestations'],
            ['RG', '707000', 'Produits accessoires'],
            ['RG', '708000', 'Autres revenus'],
            ['RG', '708100', 'Ventes de dons en nature'],
            ['RG', '708200', 'Revenus d\'usufruit'],
            ['RG', '721000', 'Production immobilisée, immobilisations incorporelles'],
            ['RG', '722000', 'Production immobilisée, immobilisations corporelles'],
            ['RG', '726000', 'Production immobilisée, immobilisations financières(1)'],
            ['RG', '736000', 'Variations des stocks de produits finis, produits intermédiaires et résiduels.'],
            ['RG', '751000', 'Profits sur créances Adhérents, clients-usagers, et autres débiteurs'],
            ['RG', '752000', 'Versement des fondateurs'],
            ['RG', '754000', 'Dons en nature courants'],
            ['RG', '754200', 'Dons en nature courants reçus à distribuer'],
            ['RG', '758000', 'Produits divers'],
            ['RG', '758200', 'Indemnités d\'assurances reçues'],
            ['RG', '758300', 'Abandons de frais par les bénévoles'],
            ['RG', '758800', 'Autres produits divers'],
            ['RG', '759000', 'Reprises de charges pour dépréciations et provisions pour risques à court terme d\'exploitation'],
            ['RG', '759100', 'Reprises provisions sur risques à court terme'],
            ['RG', '759300', 'Reprises de charges pour dépréciations sur stocks'],
            ['RG', '759400', 'Reprises de charges pour dépréciations sur créances'],
            ['RG', '759800', 'Autres reprises de charges pour dépréciations et provisions pour risques à court terme'],
            ['RG', '771000', 'Intérêts de prêts et créances diverses'],
            ['RG', '771200', 'Intérêts de prêts'],
            ['RG', '771300', 'Intérêts sur créances diverses'],
            ['RG', '772000', 'Revenus de participations et autres titres immobilisés'],
            ['RG', '772100', 'Revenus des titres de participation'],
            ['RG', '772200', 'Revenus autres titres immobilisés'],
            ['RG', '773000', 'Escomptes obtenus'],
            ['RG', '774000', 'Revenus de placement'],
            ['RG', '774500', 'Revenus des obligations'],
            ['RG', '774600', 'Revenus des titres de placement'],
            ['RG', '774700', 'Revenus des dépôts à terme et opérations assimilées'],
            ['RG', '774800', 'Autres revenus de placement'],
            ['RG', '776000', 'Gains de change financiers'],
            ['RG', '777000', 'Gains sur cessions de titres de placement'],
            ['RG', '778000', 'Gains sur risques financiers'],
            ['RG', '778100', 'Gains sur rentes viagères'],
            ['RG', '778200', 'Gains sur opérations financières'],
            ['RG', '779000', 'Reprises de charges pour dépréciations et provisions pour risques à court terme'],
            ['RG', '779100', 'Reprises de provisions sur risques financiers'],
            ['RG', '779500', 'Reprises de charges pour dépréciations sur titres de placement'],
            ['RG', '779800', 'Autre reprises de charges pour dépréciations et provisions pour risques à court terme'],
            ['RG', '781000', 'Transferts de charges d\'exploitation'],
            ['RG', '787000', 'Transferts de charges financières'],
            
            ['RH', '791000', 'Reprises de provisions et dépréciations d\'exploitation'],
            ['RH', '791100', 'Reprises de provisions pour risques et charges'],
            ['RH', '791300', 'Reprises de dépréciations des immobilisations incorporelles'],
            ['RH', '791400', 'Reprises de dépréciations des immobilisations corporelles'],
            ['RH', '792000', 'Reprises de fonds affectés et provenant des dons et legs d\'immobilisations'],
            ['RH', '792100', 'Reprises de fonds affectés aux immobilisations du projet de développement'],
            ['RH', '792200', 'Reprises de fonds affectés à un projet spécifique non consommés'],
            ['RH', '792300', 'Reprises de fonds affectés provenant de dons et legs d\'immobilisations'],
            ['RH', '792800', 'Autres reprises de fonds affectés'],
            ['RH', '795000', 'Reprises des dépréciations d\'immobilisations reçues destinées à la vente provenant des'],
            ['RH', '795100', 'Reprises des dépréciations de l\'usufruit temporaire'],
            ['RH', '795200', 'Reprises des dépréciations d\'immobilisations reçues destinées à la vente provenant des'],
            ['RH', '796000', 'Reprises des fonds reportés'],
            ['RH', '796100', 'Reprises de fonds reportés provenant de la donation temporaire d\'usufruit'],
            ['RH', '796200', 'Reprises de fonds reportés provenant de dons et legs d\'immobilisations reçues destinées'],
            ['RH', '796800', 'Autres reprises de fonds reportés'],
            ['RH', '797000', 'Reprises de provisions et dépréciations financières'],
            ['RH', '797100', 'Reprises de provisions pour risques et charges'],
            ['RH', '797200', 'Reprises de dépréciations des immobilisations financières'],
            ['RH', '798000', 'Reprises d\'amortissements'],
            ['RH', '799000', 'Reprises de subventions d\'investissement'],
            
            ['TM', '821000', 'Produits des cessions d\'immobilisations incorporelles'],
            ['TM', '822000', 'Produits des cessions d\'immobilisations corporelles'],
            ['TM', '826000', 'Produits des cessions d\'immobilisations financières'],
            ['TM', '828000', 'Produits des cessions d\'immobilisations reçues destinées à la vente provenant de dons et legs'],
            ['TM', '841000', 'Produits H.A.O. constatés'],
            ['TM', '841100', 'Produits sur donations et legs'],
            ['TM', '842000', 'Contributions volontaires en nature'],
            ['TM', '842100', 'Dons en nature HAO vendus'],
            ['TM', '842200', 'Prestations de services en nature HAO'],
            ['TM', '842500', 'Dons en nature HAO à distribuer'],
            ['TM', '843000', 'Contributions volontaires en numéraire'],
            ['TM', '846000', 'Abandons de créances obtenus'],
            ['TM', '848000', 'Transferts de charges H.A.O'],
            ['TM', '849000', 'Reprises de charges pour dépréciations et provisions pour risques à court terme'],
            ['TM', '861000', 'Reprises de provisions réglementées'],
            ['TM', '862000', 'Reprises d\'amortissements H.A.O.'],
            ['TM', '863000', 'Reprises de dépréciations H.A.O.'],
            ['TM', '864000', 'Reprises de provisions pour risques et charges H.A.O.'],
            ['TM', '868000', 'Autres reprises H.A.O.'],
            ['TM', '881000', 'Subventions d\'équilibre, État'],
            ['TM', '884000', 'Subventions d\'équilibre, Collectivités publiques'],
            ['TM', '888000', 'Autres subventions d\'équilibre'],
        ];
        
        foreach ($mappings as $mapping) {
            BilanReferenceMapping::create([
                'reference_code' => $mapping[0],
                'account_code' => $mapping[1],
                'libelle' => $mapping[2] ?? null
            ]);
        }
    }
}